language: haskell
ghc:
  - 7.8
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
  - cabal sandbox init
  - git clone https://github.com/haskell-servant/servant.git
  - cabal sandbox add-source servant/
  - git clone https://github.com/haskell-servant/servant-jquery.git
  - cabal sandbox add-source servant-jquery/
