resolver: nightly-2023-04-14

packages:
- servant/
- servant-auth/servant-auth
- servant-auth/servant-auth-client
- servant-auth/servant-auth-docs
- servant-auth/servant-auth-server
- servant-auth/servant-auth-swagger

- servant-client/
- servant-client-core/
- servant-http-streams/
- servant-docs/
- servant-foreign/
- servant-server/
- servant-swagger/

# streaming
- servant-machines/
- servant-conduit
- servant-pipes/

# allow-newer: true # ignores all bounds, that's a sledgehammer
# - doc/tutorial/

extra-deps:
- hspec-wai-0.11.1
- pipes-safe-2.3.4
