flags:
  servant-js:
    example: false
packages:
- servant/
- servant-blaze/
- servant-cassava/
- servant-client/
- servant-docs/
- servant-foreign/
- servant-js/
- servant-lucid/
- servant-mock/
- servant-server/
- doc/tutorial
extra-deps:
- base-compat-0.9.0
- engine-io-wai-1.0.2
- control-monad-omega-0.3.1
- should-not-typecheck-2.0.1
resolver: nightly-2015-10-08
