resolver: lts-14.17
packages:
- servant-client-core/
- servant-client/
- servant-docs/
- servant-foreign/
- servant-http-streams/
- servant-server/
- servant/

- servant-conduit
- servant-machines/
- servant-pipes/

# allow-newer: true # ignores all bounds, that's a sledgehammer
# - doc/tutorial/

extra-deps:
- hspec-wai-0.10.1
