flags:
  servant-js:
    example: false
packages:
- servant/
- servant-client/
- servant-docs/
- servant-foreign/
- servant-js/
- servant-mock/
- servant-server/
- doc/tutorial
extra-deps:
resolver: lts-6.0
