# Let's try to keep resolver at the first day of the month
resolver: lts-12.13
packages:
- servant-client/
- servant-client-core/
- servant-docs/
- servant-foreign/
- servant-server/
- servant/
extra-deps:
- aeson-1.4.1.0

# allow-newer: true # ignores all bounds, that's a sledgehammer
# - doc/tutorial/
