flags: {}
packages:
- servant/
- servant-client/
- servant-docs/
- servant-foreign/
- servant-server/
- doc/tutorial
extra-deps:
- attoparsec-iso8601-1.0.0.0
- http-api-data-0.3.7
- servant-js-0.9.1
- natural-transformation-0.4
- hspec-2.3.2
- hspec-discover-2.3.2
- hspec-core-2.3.2
- hspec-wai-0.8.0
- hspec-expectations-0.8.2
resolver: lts-6.27
