resolver: nightly-2026-07-03

packages:
- servant/
- servant-auth/servant-auth
- servant-auth/servant-auth-client
- servant-auth/servant-auth-docs
- servant-auth/servant-auth-server
- servant-auth/servant-auth-swagger

- servant-client/
- servant-client-core/
- servant-http-streams/
- servant-docs/
- servant-foreign/
- servant-server/
- servant-swagger/

# streaming
- servant-machines/
- servant-conduit
- servant-pipes/

- doc/tutorial/

extra-deps:
- QuickCheck-2.18.0.0
- quickcheck-instances-0.4@rev:2
- servant-js-0.9.4.2

allow-newer: true

allow-newer-deps:
- swagger2 # https://github.com/GetShopTV/swagger2/issues/264
