# Let's try to keep resolver at the first day of the month
resolver: nightly-2018-07-08
packages:
- servant-client/
- servant-client-core/
- servant-docs/
- servant-foreign/
- servant-server/
- servant/

# allow-newer: true # ignores all bounds, that's a sledgehammer
# - doc/tutorial/
