resolver: nightly-2023-04-14

packages:
- servant-client-core/
- servant-client/
- servant-docs/
- servant-foreign/
- servant-http-streams/
- servant-server/
- servant/

- servant-conduit
- servant-machines/
- servant-pipes/
- servant-io-streams/
- servant-swagger/

# allow-newer: true # ignores all bounds, that's a sledgehammer
# - doc/tutorial/

extra-deps:
- hspec-wai-0.11.1
- pipes-safe-2.3.4
