resolver: lts-11.8
packages:
- '.'
extra-deps:
- base-compat-batteries-0.10.1
- base-compat-0.10.1
- hspec-discover-2.5.0
- hspec-core-2.5.0
- hspec-2.5.0
# aeson pre-1.3.1.0 has an upper bound on `base-compat-batteries` that preclude
# the 0.10.1 that we depend on
- aeson-1.3.1.0
flags: {}
extra-package-dbs: []
