name: nix ci
on: 
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix -L flake check
      - run: nix -L build .#servant-quickcheck
      - run: nix -L build .#ghc94-servant-quickcheck
      - run: nix -L bulid .#ghc98-servant-quickcheck
